source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’11.0’
use_frameworks!
inhibit_all_warnings!

target ‘TravelHelper’ do
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SwiftyJSON'
    pod ‘Hero’
    pod 'IGListKit'
    pod 'SnapKit'
    pod 'RxSwift', '~> 4.0.0-alpha.0'
    pod 'RxCocoa', '~> 4.0.0-alpha.0'
end

post_install do |installer|  
    installer.pods_project.targets.each do |target|
        is_should_swift32 = ['Hero'].include?(target.name)
        target.build_configurations.each do |config|  
            config.build_settings['ENABLE_BITCODE'] = 'YES'
            config.build_settings['SWIFT_VERSION'] = is_should_swift32 ? '3.2' : '4.0'
        end  
    end  
end 