source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’11.0’
use_frameworks!
inhibit_all_warnings!

target ‘TravelHelper’ do
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SwiftyJSON'
    pod ‘Hero’
    pod 'IGListKit'
    pod 'SnapKit'
    pod 'RxSwift'
    pod 'RxCocoa'
end

post_install do |installer|  
    installer.pods_project.targets.each do |target|  
        target.build_configurations.each do |config|  
            config.build_settings['ENABLE_BITCODE'] = 'YES'
        end  
    end  
end 